CREATE DATABASE ToDoList
GO

USE ToDoList
GO

CREATE TABLE ToDoList(
    ToDoListId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ToDoListName NVARCHAR(255) NOT NULL,
    ToDoListDescription NVARCHAR(1000) NULL,
    ToDoListStartDate SMALLDATETIME NOT NULL,
    ToDoListEndDate SMALLDATETIME NOT NULL,
    ToDoListOrder TINYINT NOT NULL,
    ToDoListDuration REAL NOT NULL,
    ToDoListExperience NVARCHAR(1000) NULL
);